#!/bin/bash
# Hi Sir
# Student Information
# Name- Japsimran Singh
# Student Number- 200516405
# First of all i created a variable for the first peice of report.
partOneVariable=$(cat <<EOF
---------------------
System Information
---------------------
Hostname: $(hostname)                      
OS: $(source /etc/os-release && echo $PRETTY_NAME) 
Uptime: $(uptime -p)                              
---------------------
EOF
)

# Now i will describe Hardware Information.
# Comman i will use will be lscpu
cpuName=$(lscpu | grep 'Model name' | awk -F': ' '{print $2}')
cpuSpeed=$(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /size:/{print $2; exit}')
max_cpuSpeed=$(sudo lshw -class processor | awk '/description: CPU/{p=1} p && /capacity:/{print $2; exit}')
cpuRAM=$(sudo lshw -short -C memory | grep -i 'system memory' | awk '{print $3}')
cpuDisks=$(lsblk --output NAME,SIZE,TYPE,MOUNTPOINT,LABEL --exclude 7 | awk '!/loop/ {printf "%-8s %-8s %-4s %-8s %-7s %s\n", $1, $2, $3, $4, $5, $6}')
graphicsCard=$(lspci -nnk | grep -i 'VGA' | awk -F': ' '{print $2}' | uniq)

# Now i will set up the Network Information
# first Command will be hostname -f
FqdnName=$(hostname -f)

# next Command will be ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}'
hostIPAddress=$(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')
# NOW Command ip r | awk '/default/ {print $3}' i will use
hostGatewayIP=$(ip r | awk '/default/ {print $3}')
hostDNS=$(grep -E '^nameserver' /etc/resolv.conf | awk '{print $2}')
interfaceName=$(sudo lshw -class network | grep -E 'description|product|vendor|physical id|logical name' | awk -F ':' '{print $1 ": " $2}')
networkIP=$(ip a show dev $(ip r | awk '/default/ {print $5}') | awk '/inet / {print $2}')

# Now i will move to next part:System Status
# Command who will be used to check which users are logged in.
loggedUsers=$(who | awk '{print $1}' | sort | uniq | paste -s -d ',')
# next Command will be df -h
diskSpace=$(df -h)
totalProcessCount=$(ps -e | wc -l)
loadAVG=$(uptime | awk -F'[a-z]:' '{print $2}')
allocatedMemory=$(free -h | awk '/^Mem:/ {print "Type\tTotal\tAvailable"; print $1 "\t" $2 "\t" $7}')
portsListening=$(ss -tuln)
# Command for ufw rules:
UFWRules=$(sudo ufw status numbered | grep -v 'Status: active')
# now i will Display the information
echo " System Report generated by $(whoami), $(date)"
echo "$partOneVariable"
echo "Hardware Information"
echo "---------------------"
cat <<EOF
CPU: $cpuName
Speed: $cpuSpeed
MAX Speed: $max_cpuSpeed
RAM: $cpuRAM
Disks: $cpuDisks
Video card: $graphicsCard
---------------------
EOF
echo "Network Information"
echo "---------------------"
cat <<EOF
FQDN: $FqdnName
Host Address: $hostIPAddress
Gateway IP: $hostGatewayIP
DNS Server: $hostDNS
Network Interface Information:
$interfaceName
IP Address: $networkIP
---------------------
EOF
echo "System Status"
echo "---------------------"
cat <<EOF
Users Logged In: $loggedUsers
Disk Space:
$diskSpace
Process Count: $totalProcessCount
Load Averages: $loadAVG
Memory Allocation:
$allocatedMemory
Listening Network Ports:
$portsListening
UFW Rules: $UFWRules
---------------------
EOF
# Finish.